### ISSUE TITLE
app2luggage.rb fails

### ISSUE THREAD

**Issue by workflowsguy** [unixorn/luggage#61]
When trying to create a package on 10.9.5 for Prizmo 2 with the command line

`sudo app2luggage.rb --application "/Applications/Prizmo.app" --package-id "Prizmo 2"  --reverse-domain com.creaceed.prizmo2`

I get

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ftools (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bin/app2luggage.rb:30:in `<main>'
```

Thanks!

**Comment by juttmartin** [comment]
The issue you are having is because you are using the macOS supplied ruby and running as sudo will point to that. As of right now I'm running macOS 10.12.3 and I have it working just fine. All I did was install Ruby for my account and is the preferred method. Just follow this guide on how to get setup: [Ruby Setup macOS](http://railsapps.github.io/installrubyonrails-mac.html)

After that you will need to most likely install additional gems. The gems I installed were trollop & ftools. Once I had this the dependancies went away and app2luggage worked fine. You won't need to run this elevated at this point since everything is configured under your account. Hope this helps out.
